### ISSUE TITLE
Any chance of build instructions?

### ISSUE THREAD

**Issue by paul-hammant** [airmeter-io/AirMeter.IO.Firmware#1]
Pre reqs?  Builds on all of Mac/Win/Lin?

Cheers.

**Comment by FurballTheGreat** [comment]
Hi,
The documentation is still WIP but you can find ESP32 build instructions using ESP-IDF at https://airmeter.io/make/esp32/firmware_build

It has been built on Win and Linux, as ESP-IDF supports being built on Mac I see no reason this will be a problem.

All pre-requisites are pulled as git sub modules or already included in the source code. So you just need a functioning ESP-IDF 4.4 build environment.

HTH!
